name: Deno CLI Action

on:
  push:
    branches: ["main", "nexting"]
  pull_request:
    branches: ["main", "nexting"]
  workflow_dispatch:

jobs:
  deno-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Deno CLI Check
        run: deno run --allow-read --allow-env scripts/deno-cli.ts --check
